### ISSUE TITLE
GUIDs on all achievement classes

### ISSUE THREAD

**Issue by jonasswiatek** [jonasswiatek/strokes#10]
I'm considering if we might as well now apply a GUID Attribute to all Achievement implementations. The reason is that currently I store the Achievement name in an XML File on the users hard drive whenever they complete and achievement, and look up in this to see if an achievement is completed (or also if it isn't, and therefore should be scanned for).

Problem with that is of course that if we rename an achievement (or if the user changes the language of the extension!!!) that the achievements will then appear as uncompleted.

Feedback, ideas, thoughts and/or death threats?

**Comment by clausjoergensen** [comment]
GUID sounds fine. Do it!

**Comment by jonasswiatek** [comment]
Done
