### ISSUE TITLE
New Data Storage

### ISSUE THREAD

**Issue by jonasswiatek** [jonasswiatek/strokes#11]
Currently we just a flat XML file in the users AppData directory to store the users achievements (and settings whenever we get those made). Does anyone have any input to this? I was thinking about using SQLite or something instead so we can do some nice statistics or something by simply using SQL Queries.

**Comment by jonasswiatek** [comment]
Considering that it's bad practice to bind to a single data provider, I'm going to turn the Strokes.Data project into two parts:

Strokes.Service and Strokes.Data, and all contracts and model will be placed in Strokes.Core. I'm also going to throw StructureMap into the mix to provide IoC.

**Comment by timdams** [comment]
Hey, what do you mean with "Considering that it's bad practice to bind to a single data provider, "?  (I'm here to learn ;)  )

**Comment by jonasswiatek** [comment]
It's a pretty common pattern to decouple the data store model from the application data model. It' ensures that replacing a data provider (e.g. SQLite vs. XMLFile) will only require recoding in one layer of the application. Where as if you make your application depend directly on entities that belong to your data storage, you'll have to change all that.

**Comment by jonasswiatek** [comment]
I've added Structuremap for Indirection and done some refactoring in the data section

**Comment by vlad2135** [comment]
Yep, why not to switch to SQL. Other thing you may to think about (in cource of online achievement competition) is a protection from achievement storage tampering.

**Comment by jonasswiatek** [comment]
Well, tampering with the local achievement list isn't really a concern, since actual verification on the website (when that one is done!) will rely on the user approving that a sample of the source code is transmitted to the server for server-side verification of the achievements.

Anti-cheating is nearly impossible in any regard, since people can just share source code that would unlock everything anyway ;)

**Comment by clausjoergensen** [comment]
I'd prefer the ability to cheat. No reason to make it more complicated than so. Case closed?

**Comment by jonasswiatek** [comment]
Yea I'll close it for now. Unless we encounter some sort of concurrency issue with the XML file, I'll just leave it as it is.
