### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by jonasswiatek** [jonasswiatek/strokes#12]
We should add some settings to the settings tab.

Off the top of my head:
1) Localization selection
2) Reset Achievement Progression
3) Enable Strokes in ALL projects (not only in Achievement Projects)

**Comment by clausjoergensen** [comment]
1) Easily done
2) Don't we already have that?
3) Is the technical solution present for this, or is it something we need to code before it's incorporated in the UI ?

**Comment by jonasswiatek** [comment]
2) Yup, it's there - mostly just wrote it there to have the entire list here
3) Yea, it's there - we just need the setting to be set somewhere, and I can read it out in the detection dispatcher.

**Comment by jonasswiatek** [comment]
I'm guessing we need to add an XML Repository for the settings as well. I'll do that tomorrow.

**Comment by jonasswiatek** [comment]
I've made a SettingsRepository now - I haven't tested it, but I assume that it'll work.

Get a reference to it by:

``` csharp
var settingsRepo = ObjectFactory.GetInstance<ISettingsRepository>();
var settings = settingsRepo.GetSettings();
settings.EnableInAllProjects = true/false;
settings.PreferredLocale = "ru-RU";

settingsRepo.SaveSettings(settings);
```

I can't figure out how to get that Command-thing working in the WPF for AchievementPane - can you implement the rest Claus?

**Comment by clausjoergensen** [comment]
Yep, will do.

**Comment by jonasswiatek** [comment]
I've implemented this - Claus can you look at the disaster that is my ComboBox I've put into the AchievementPane XAML?
