### ISSUE TITLE
Add unit test to BasicAchievements-project

### ISSUE THREAD

**Issue by jonasswiatek** [jonasswiatek/strokes#13]
To test for the following:

1) That no achievements have duplicated guids
2) That all achievements have a valid guid

**Comment by timdams** [comment]
It will be lots of work, but shouldn't we also do this for every achievement we write?

**Comment by jonasswiatek** [comment]
Ah, no I'm not going for 100% code coverage. Just a test that ensures that the guids are unique

**Comment by jonasswiatek** [comment]
I've added a unit testing system for testing all of the achievement types. Have a look in the Wiki Article: https://github.com/jonasswiatek/strokes/wiki/Achievement-Unit-Testing-(you-know-you-want-it!)

**Comment by timdams** [comment]
Shouldn't we agree on some format on how we organize the achievement tests? Because we can't simply throw them all in one folder.

1) We could simply have the same folders as in the basicachievements project (Arrays, Basic, etc.)
2) Or have one testfile per category?

I'm new to working with (unit)tests so  the following might be shot down immediatelly:
3) Why not write the unit test in the same file as the achievement? That way we don't get inconsitencies when achievements are moved around or renamed. 

By the way,don't we have to incorporate the GUID in this story somehow?

**Comment by jonasswiatek** [comment]
I can easily add support for sub directories inside the TestCases directory of the BasicAchievements.Test project - you're right that having everything in one big folder isn't very effective.

Having one test file per category is viable, but it has the issue that the more achievements you test for in one code file, the less precise it is - since you can't with certainty tell which lines of code unlocked what. I think having one testcase per achievement is the best way to go about it - it'll also help fine tune the acheivement definitions.

Having the unit test in the same file as the achievement poses a challenge, in that the achievement code it self is then tested for achievements - because the achievement dispatcher looks at the entire file when testing.

GUIDS don't need to be a part of it, since we're referencing the Achievements by strongtyping ( typeof(SomeAchievement) ) - so if you rename an achievement (with Visual Studios refactor feature), it'll automaticly update everything in the unit test as well - or alternatively you'd get a compile time error about it.

**Comment by jonasswiatek** [comment]
I've added a unit test to ensure integrity of the RESX files. I think this will VASTLY help this process.

It tests if:
1) All achievement descriptors use proper localization
2) If all references @Keys actually exist in the RESX file for the culture being tested
3) Tests if the RESX defines un-used Keys

**Comment by timdams** [comment]
Works like a charm!

**Comment by jonasswiatek** [comment]
Awesome!
