### ISSUE TITLE
MSDN / Wikipedia / SO link parameter on Descriptor Attribute

### ISSUE THREAD

**Issue by jonasswiatek** [jonasswiatek/strokes#16]
Add extra attribute to achievements containing a url to MSDN/WIKI/STACKOVERFLOW page with more information on the achievement

**Comment by clausjoergensen** [comment]
We should consider a "details" view for the individual achievements if we want to extend them with much more information.

**Comment by jonasswiatek** [comment]
What about added it as a "HintUrl"-member on the Descriptor?

**Comment by clausjoergensen** [comment]
I was more concerned about the display of the items.

**Comment by jonasswiatek** [comment]
How about that when the achievement is clicked, it's height expands to make room for more information?

We could contemplate saving the code that actually unlocks the achievement as well for future reference and / or some sort of 127.0.0.1 e-peening

**Comment by clausjoergensen** [comment]
That could work out. I'll have a look at it.

**Comment by jonasswiatek** [comment]
This has been added, and is used like this: https://github.com/jonasswiatek/strokes/blob/7cc96a509ad8ca3d4b4af93d63e182de29173788/source/Strokes.BasicAchievements/Achievements/Generics/CreateGenericClass.cs

It's available on the Achievement-class as Uri HintUri

**Comment by clausjoergensen** [comment]
So it's implemented now. However, I'm not sure how intuitive it is. The user won't necessary know to click a achievement for more information.

**Comment by jonasswiatek** [comment]
Looks good - but yea it's pretty secret that you can click there. What if it automatically expands it, if the mouse is hovered over the element for more than x seconds? like, to show the user that this expands.

**Comment by clausjoergensen** [comment]
Could be done, but I don't think hovering is ideal either. Was thinking some form of identifier, perhaps an arrow or something.

**Comment by jonasswiatek** [comment]
Mm, yea - perhaps with a text next to it "click to expand" that is only visibly with the element is hovered

**Comment by clausjoergensen** [comment]
That might work out. I'll see what I can do.

**Comment by jonasswiatek** [comment]
This is implemented - yay
