### ISSUE TITLE
AchievementTree

### ISSUE THREAD

**Issue by jonasswiatek** [jonasswiatek/strokes#17]
I've added this now - see https://github.com/jonasswiatek/strokes/commit/5d3f7ada608a7c1edb3f089b89b64ddaf1b27447#diff-0 for an example.

The Achievement-DTO (I renamed AchievementDescriptor to Achievement), that the Strokes.GUI project receives from the IAchievementRepository now contains two extra data members:

DependsOn and Unlocks - both are IEnumerable of Achievement. The Strokes.GUI project should display these in some fashion. Maybe you can have a stroke of inspiration Claus? ;)

Tim: it's ready for you to enter the dependencies now - and a side feature is that one achievement can require one or more achievements to be completed before it can unlock.

**Comment by clausjoergensen** [comment]
If we're going World of Warcraft style, we'll not display the achievements that depends on others to be completed first. And as for unlocks, I'm thinking something like a the "reward" style in (a ribbon of a sort).

**Comment by jonasswiatek** [comment]
Yea, I was thinking World of Warcrafts Achievement UI as well.

**Comment by clausjoergensen** [comment]
Need to be prettified, but the basic part of is implemented now.

**Comment by jonasswiatek** [comment]
And it seems it works! I've added dependencies to all the array achievements to test it.

**Comment by timdams** [comment]
Really like what you done there Jonas and Claus. Lovely job :)

**Comment by timdams** [comment]
PS Now I also understand why the total achievement count suddenlt is dropped (my first thought was that someone had deleted some achievements).

Perhaps we should show in the UI behind each category how many achievement in total there actually are to be earned? Eg. Arrays (0/5) (+5 hidden)
