### ISSUE TITLE
Icons from http://www.iconarchive.com/ ?

### ISSUE THREAD

**Issue by timdams** [jonasswiatek/strokes#20]
Perhaps we could salvage some  icons from http://www.iconarchive.com/ instead of using my handdrawn thumbs-up icon ? 

However, perhaps we should first have one icon per category. 
I'll have a look at this later on; but other deas more than welcome ofcourse.

**Comment by clausjoergensen** [comment]
From a pure aesthetic point of view, I would say that random ugly icons for each category would look very ugly, compared to the more streamlined layout we have now.

For the achievements itself, it's a much better idea, but I doubt we'll find icons in high enough resolution, that also suits the layout style.

**Comment by timdams** [comment]
So issue closed then :D

Tim Dams

---

Sent from my Windows Phone ( sorry for possible typos or short answer)

**Comment by jonasswiatek** [comment]
I've talked with a colleague of mine that does some pretty good graphical work - hes agreed to make some icons in the near future
