### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by clausjoergensen** [jonasswiatek/strokes#21]
What's our actual plan with it? If we're planning to do a somewhat complete beta-release, should we "hide" it from the UI for now?

**Comment by timdams** [comment]
Perhaps leave it there with small note/teaser "coming soon"?

**Comment by jonasswiatek** [comment]
It was originally meant for the online integration (see your friends progress)

**Comment by jonasswiatek** [comment]
Lets re-enable it when the online stuff is present in this plane of existence
