### ISSUE TITLE
Satellite assemblies not included in VSIX file

### ISSUE THREAD

**Issue by jonasswiatek** [jonasswiatek/strokes#23]
Localizations aren't deployed into the VSIX file. I think this needs to be configured some how.

In reality this means that localizations don't work in the actual extension.

**Comment by clausjoergensen** [comment]
Don't think we're including _any_ reference assemblies in the VSIX right now? Default configuration is not to include them.

**Comment by jonasswiatek** [comment]
Well it includes build references, but the nl, da-DK and ru-RU folders are not put into the VSIX file.

The vsix file's content can be viewed with 7-zip or similar

**Comment by jonasswiatek** [comment]
Sweet merciful Jesus, getting this to work required me to read a fuckton of documentation on the MSBuild tool.

How to do this is worth saving:

![Satellite Assembly Include](/jonasswiatek/strokes/raw/master/docs/vsix_satelliteassemblies.png)
