### ISSUE TITLE
Some practical tools for NRefactory

### ISSUE THREAD

**Issue by jonasswiatek** [jonasswiatek/strokes#29]
We can do much more complex analysis with NRefactory if we want to. The current framework I've written for it is only meant to do simple stuff like "is [something] declared" or "is someone using a for loop".

However, if the achievement needs to span for instance "is the user using xyz in 5 different methods, and implementing a class that implements another class that implements an interface" then it's a bit more complex - but the good news is that it can be detected with very litle code - I just need to write some more reusable visitors.

Is this something we need now?

**Comment by clausjoergensen** [comment]
> Is this something we need now?

Yes

**Comment by jonasswiatek** [comment]
We've made quite a few of these in NRefactoryHelper so far - so I'll close this as a separate issue
