### ISSUE TITLE
On levels and future directions of Strokes

### ISSUE THREAD

**Issue by timdams** [jonasswiatek/strokes#33]
Hi guys,

I wanted your ideas on the following.
Currently, there's 2 things happening: 

a) we're creating a lot of 'low level' achievements (150+) . With low level I mean stuff that students with max of 2 years programming experience can easily solve.
b) we are starting to think about more advancement achievements

Two things will (probably) happen
1° I can think of 1000 of low-level achievements where we for example simply have lots of generic stuff for each type (just like the ones in the primitive type) etc. I could create them (with pleasure) but that will result in an incredible large base of simple stuff all unlockable from the start.
2° The more advanced ones might not be very interesting for beginning programmers and might thus a bit 'clutter' the "unlockable stuff overview " unless we hardwire lotse of dependencies...which then might get cumbersome and artificial.

With these 2 directions we might need to introduce a form of 'levels': user earn 'points' by unlocking stuff and the higher their level/points, the more new/advanced stuff they can unlock. This way we can keep the achievement tree of a bit relaxed (i.e. we don't need to build in lots of dependencies to lower level stuff ) and we can simply unlock stuff once they reach a level. (but still keep the achievement tree also ofcourse).
Second, we can distribute the lower level stuff, that is all bit identical , over several 'levels'. For example: level one only unlocks the int stuff of primitive type and only the if stuff; level 2 also the double and if else; level 3 char and while; etc. That way our achievement tree isn't forced to hard and we still give the users more of a sense of progress.

**Comment by clausjoergensen** [comment]
1) With the `DependsOn` properties on the achievements, we already created a kind of "levels", where you can't see harder achievements before you unlocked the easier ones. 

2) So far things that's locked, aren't visible in the UI. 

I think the biggest task is to structure what achievements needs to depend on what.

**Comment by timdams** [comment]
"I think the biggest task is to structure what achievements needs to depend on what."

But this might exactly impose a bit of a fake hierarchy since most of the basic achievements can all be considered 'equal' and independent of one another. If we impose a strict hierarchy/structure we might get bottlenecks where students aren't able to progress because they didn't unlock that one specific achievements. With points/levels we make these dependencies a bit less strict and especially are able to contain a consistent feeling of progression (compare to WoW and other experience-based games where you even feel like progression by simply killing (low level)stuff without earning those much wanted achievements)

**Comment by jonasswiatek** [comment]
I think this is better solved by visually displaying the achievement tree as a sort of Flowchart-like image, so it's clear which achievements are currently available to you, and you need to unlock to progress further.

In the achievement progress list:
I think showing all achievements in the lists is best, but the ordering is:

IsUnlockable (true -> false), By Name ASC

Locked achievements are visibly disabled some how, and there is a link to it's requirements, so the user can easily jump to them (exactly like World of Warcraft's Achievement list)

**Comment by jonasswiatek** [comment]
I'm closing this for now, since the ideas we're talking about here are being tried out by my endevour to make a tool that helps organize the achievements, and Claus' work on a visualization of the achievement hiearchy
