### ISSUE TITLE
"Freeze" of master branch

### ISSUE THREAD

**Issue by jonasswiatek** [jonasswiatek/strokes#34]
Right now me and Claus are upgrading the NRefactory implementation to NRefactory version 5.

There is a lot of refactoring of the achievements going on - you can check out the nrefactory5 branch to check it out, but we'll merge it into master as soon as we're done ;)

**Comment by timdams** [comment]
Ok, looking for ward to that!
Your timing is excellent since this week will be crunchtime for school-stuff (yeah; even teacher have that from time to time :p   ) so not much Strokes for me this week anyhow!
Give'm hell lads!

(you'll get an achievement for it:p)

**Comment by clausjoergensen** [comment]
We'll will do! Enjoy rating the exam papers ;-)

**Comment by jonasswiatek** [comment]
This branch is ready for Quality Control. Everything has been upgraded except two achievements I couldn't figure out what did from their description and code.

**Comment by timdams** [comment]
Probably my encrypted achievements :P which 2 are they?

Tim Dams

---

Sent from my Windows Phone ( sorry for possible typos or short answer)

**Comment by jonasswiatek** [comment]
ThrowExceptionLongMessageAchievement and ProgramWithStartupParamsAchievement

**Comment by timdams** [comment]
ThrowExceptionLongMessageAchievement : occurs if a new exception is thrown with the Message parameter longer dan X number of chars
ProgramWirhStartupParamsAchievement: occurs if usres tries to create a console application that accepts input parameters that are processed in side the main .Basically I check if a) the main has a parameter called args . b) I naievely check if the args parameter isutilized somewher ei the code...:

**Comment by jonasswiatek** [comment]
All achievements are now unit tested - hoooray.

Now, I fixed a lot of bugs in the achievements while doing this, and we really need these unit tests to be in working order to make sure things works as we want them to -- so remember to write unit tests for all new achievements ;)

When you run the unit tests (CTRL+R, A), there are two unit tests you need to pay attention to:

TestAchievements: Fails if an ExpectUnlock isn't filled, or if an achievement unlocks something that isn't expected
TestCoverage: This test fails if there is an achievement that isn't unit tested

Both these tests must always pass :D

If you could check out the nrefactory5 branch, and try the extension and see if everything works as we want, then I'll merge nrefactory5 into master in a day or two

**Comment by jonasswiatek** [comment]
Do a pull on master and we'll all be in synch.

For those of you that have the nrefactory5 branch, I recommend that you delete it with "git branch -d nrefactory5"
I'm going to delete the nrefactory5 branch from github tonight.

**Comment by jonasswiatek** [comment]
For reference, the following commands are used for this:

Switch back to master branch: **git checkout master**
Pull the updates to the master branch: **git pull**
Delete the nrefactory5 branch: **git branch -d nrefactory5**

The above is ofcourse only relevant if you've pull the nrefactory5 branch from the remote to begin with!

**Comment by timdams** [comment]
wow, very nice job... Especially considering that I wanted to write the test to debug my code. On the other hand, isn't it good practice to let someone else write the tests than the coder himself?

hope you didn't find too many silly bugs and mostly very hard to solve ones? :-O

**Comment by jonasswiatek** [comment]
nrefactory5 branch is now deleted
