### ISSUE TITLE
Twitter/Facebook Integration

### ISSUE THREAD

**Issue by clausjoergensen** [jonasswiatek/strokes#35]
Twitter/Facebook Integration -- because we can.

Biggest issue is a authentication model. I think with a browser component, we can avoid having to handle authentication entirely, which should free us from any security issues.

**Comment by jonasswiatek** [comment]
Integrating oauth without a browser component borders impossiblity. I was thinking originally, that I'd integrate stuff like Twitter and facebook on the website, and then just make a proper integration between the extension and the website.

**Comment by clausjoergensen** [comment]
Oh yeah, good point about Facebook as well.

**Comment by timdams** [comment]
Good idea!

**Comment by jonasswiatek** [comment]
I'm closing this for now
