### ISSUE TITLE
New Branch: Archidev

### ISSUE THREAD

**Issue by jonasswiatek** [jonasswiatek/strokes#37]
It's short for "Achitectural Development" - I'm doing some very extensive refactoring of in particular the Strokes.Core project and how it abstracts different things in the system.

You're welcome to follow it, and Claus: at some point this week, if you've got time, we need to rework the Adornments things when you click the magnifier. There isn't really any reason why this event is propergated through Strokes.Core - it's exclusively a concern between Strokes.GUI and Strokes.VSX - in practise I'm imagining that Strokes.GUI exposes an event that is fired whenever it needs a particular document to be displayed, and that it internally handles the entire wireing of the Magnifier icons on-click.

Anyway, I'll implement as much of it as I can my self, and then just create an issue for it.

Oh yea, lastly: all this is to support achievements that interacts directly with Visual Studios Extension model, rather than static analysis.

**Comment by jonasswiatek** [comment]
And: this branch doesn't prevent any other work to be done in the master branch - in particular Strokes.GUI and Strokes.BasicAchievements only see modifications in very specific places, so no merge conflicts should arise (except maybe csproj files - but those never merge anyway)

**Comment by timdams** [comment]
"all this is to support achievements that interacts directly with Visual Studios Extension model". What type of achievements will this introduce then (so that I can start dreaming up new ones :)  )

**Comment by jonasswiatek** [comment]
Could be that you've run a successful unit test run, or added a Linq2SQL component to the project

**Comment by timdams** [comment]
http://images.memegenerator.net/instances/400x/10769832.jpg

**Comment by jonasswiatek** [comment]
This has been merged

**Comment by timdams** [comment]
Got some progtime tonite. Any tips ?:D

Tim Dams

---

Sent from my Windows Phone ( sorry for possible typos or short answer)

**Comment by jonasswiatek** [comment]
Hmm - yea what to do...

Currently the feature achievement project isn't quite ready yet. One thing we need to do one of these days, is to try out all the achievements. I think they're all quite accurate, but they're still only as good as the unit tests that governs them.

Or, we could probably use some more challenges - or at least some ideas on which challenges we want.
