### ISSUE TITLE
GUID register of all achievements

### ISSUE THREAD

**Issue by clausjoergensen** [jonasswiatek/strokes#39]
For the "depends on", I think it could be cool, if we at some point could get a list of achievements with their respective GUIDs, on the website or similar.

Would make it easier to find the necessary GUID for the DependsOn attribute value.

**Comment by jonasswiatek** [comment]
I can create the data feeds for that pretty easily. Then we can make a utility-project that shows it.

**Comment by timdams** [comment]
Second that!

Tim Dams

---

Sent from my Windows Phone ( sorry for possible typos or short answer)

---

From: Claus Jørgensen
Sent: 30/10/2011 12:16
To: Tim Dams
Subject: [strokes] GUID register of all achievements (#39)

For the "depends on", I think it could be cool, if we at some point could get a list of achievements with their respective GUIDs, on the website or similar.

Would make it easier to find the necessary GUID for the DependsOn attribute value.

## 

Reply to this email directly or view it on GitHub:
https://github.com/jonasswiatek/strokes/issues/39

**Comment by jonasswiatek** [comment]
If this is for actually organising the graph of achievements, then I think developing a tool that simply modifies the C# code is in order. I'll see what I can whip up.

**Comment by timdams** [comment]
Finally! About time claus 😀
