### ISSUE TITLE
AchievementPane.xaml designer errors

### ISSUE THREAD

**Issue by vlad2135** [jonasswiatek/strokes#4]
I can not work fully with the subject wpf designer page because of the following errors that appear when I try to open AchievementPane.xaml:

Error   1   '{DependencyProperty.UnsetValue}' is not a valid value for the 'System.Windows.Controls.Panel.Background' property on a Setter. Strokes.GUI\Views\AchievementPane.xaml  49  45  Strokes.GUI
Error   2   '{DependencyProperty.UnsetValue}' is not a valid value for the 'System.Windows.Controls.Border.BorderBrush' property on a Setter.   Strokes.GUI\Views\AchievementPane.xaml  62  28  Strokes.GUI
Error   3   '{DependencyProperty.UnsetValue}' is not a valid value for the 'System.Windows.FrameworkElement.FocusVisualStyle' property on a Setter. Strokes.GUI\Views\AchievementPane.xaml  63  130 Strokes.GUI
Error   4   '{DependencyProperty.UnsetValue}' is not a valid value for the 'System.Windows.FrameworkElement.FocusVisualStyle' property on a Setter. Strokes.GUI\Views\AchievementPane.xaml  106 127 Strokes.GUI
Error   5   '{DependencyProperty.UnsetValue}' is not a valid value for the 'System.Windows.FrameworkElement.FocusVisualStyle' property on a Setter. AchievementPane.xaml    113 124 Strokes.GUI

Any advice how to fix it?

**Comment by jonasswiatek** [comment]
Windcape: sounds like something you'll know how to fix.

**Comment by vlad2135** [comment]
Can you at least reproduce this bug, Jonas?

**Comment by jonasswiatek** [comment]
Yup, the error message appears here as well. It appears to compile just fine though. Claus will probably look into it tomorrow - however, until then you should still be able to do the localization in the resx-files in the properties section.

The localizations for the GUI (everything that isn't achievement specific text), for russian goes into the Strokes.GUI/Properties/Resources.ru-RU.resx file

For the achievements:
Strokes.BasicAchievements.VSX/Properties/AchivementResources.ru-RU.resx and AchivementCategoryResources.ru-RU.resx

For a reference check the AchivementCategoryResources.resx and AchivementResources.resx files

It should automatically load localizations from the ru-RU files if your windows' locale is set to Russian.

**Comment by jonasswiatek** [comment]
I've made a small update to the Strokes.Console project, which is a small console tool that'll launch the achievement detection code without running a full Visual Studio Experimental Instance. In the beginning of the file you can specify a culture to use (e.g. da-DK or ru-RU).

The TestFile.cs-file is the source code that it'll check for achievements, so modify that to make it unlock and achievement you want to test for. This should help a bit with the localisation.

To get the changes from this repo, I think you have to add this one as a remote to yours, and then do a "git pull [remotename] master" - and it'll synch up.

**Comment by clausjoergensen** [comment]
Don't use Visual Studio's designer. It's crapshit. Get Expression Blend if you really want to do WPF work.  Also, I can't spell Achievement. So /shoo!

(And damn you Jonas, Blend needs a x86 build configuration!)

**Comment by jonasswiatek** [comment]
Then that's why we had x86 configs. Feel free to set the GUI project back to x86. Not like it actually need to be 64 bit.

**Comment by clausjoergensen** [comment]
Yep, done that now. And fixed my spelling errors.

**Comment by jonasswiatek** [comment]
It is kinda crappy that the default xaml editor is so weak.
