### ISSUE TITLE
Array.Clear achievement doesn't work

### ISSUE THREAD

**Issue by clausjoergensen** [jonasswiatek/strokes#6]
The Array.Clear achievement doesn't work.

**Comment by timdams** [comment]
This only works if you use the full specifier: System.Array.Clear()

So following example unlocks the achievements:

```
        int[] t = new int[] {1, 2, 4};            
        System.Array.Clear(t,0,3);
```

**Comment by clausjoergensen** [comment]
But nobody is ever going to use a fully qualified name. Could we modify it to just be Array.Clear(...) then?

**Comment by timdams** [comment]
Yeah, we had this dicussion with Jonas before. I think he put it on his to do list :)
Basically this issue counts for all the achievements in the \MethodCalls (such as Console etc.)

Thing is, certain people prefer to use System.Console.whatever while other prefer Console.whatever  (especially for beginning students who don't grasp the concept of namespaces yet, the first way is actually preferred)

**Comment by clausjoergensen** [comment]
I'll have a look at it, and see if I can fix it then. Must be a way to make it ignore namespaces.

**Comment by clausjoergensen** [comment]
Fixed.

**Comment by clausjoergensen** [comment]
Of course, if you happen to write `System.Array.Clear` now, it doesn't detect it, since the achievement only checks the **precise** call-path.

I've added global ignore for the `System` namespace, let me know if you guys think it's a bad thing.

**Comment by clausjoergensen** [comment]
Alternative solution could be to specify both with and without `System` in front, in the achievement constructor:

```
public class HelloWorldAchievement : AbstractMethodCall
{
    public HelloWorldAchievement(): base("System.Console.WriteLine", "Console.WriteLine")
```

But that's more work for us. And `System` is generally ignored.

**Comment by jonasswiatek** [comment]
I think ignoring the System namespace is good for now - but making it resolve the namespaces from the possible using clauses is more reliable in the long run.

**Comment by clausjoergensen** [comment]
We need to find a way to pass that along to the AbstractMethodCall then. I don't think we're passing along the entire AST node right now.
