### ISSUE TITLE
Scroll to code that unlocks achievement

### ISSUE THREAD

**Issue by timdams** [jonasswiatek/strokes#7]
When a user clicks the 'magnyfier glass' after unlocking something; the code is highlighted. However, if this code is currently not shown, we should scroll the page to make sure the code is vissible (or give the user a hint that the highlighted code is somewhere up or down the page).

**Comment by jonasswiatek** [comment]
Yea - I've been trying to do that but can't figure out the VSX stuff to do it. But some day! :D

**Comment by clausjoergensen** [comment]
That was super easy:

```
layer.TextView.ViewScroller.EnsureSpanVisible(span, EnsureSpanVisibleOptions.AlwaysCenter);
```

**Comment by jonasswiatek** [comment]
Well damn. I remember stumbling around intellisense for like... two hours and then just throwing in that comment about you probably found.

**Comment by jonasswiatek** [comment]
I can confirm that this appears to work. Nice!
