### ISSUE TITLE
Refactored a lot of stuff

### ISSUE THREAD

**Issue by jonasswiatek** [jonasswiatek/strokes#9]
Sup guys,

I've moved some stuff around:
1) Strokes.BasicAchievements.Vsx -> Strokes.BasicAchievement (and it's just a standard class library now - improves build time)
2) Strokes.Challenges.Student -> Strokes.Challenges
3) Strokes.ChallengeTemplate -> Strokes.VsTemplate (and renamed to Strokes Achievement Project)
4) Strokes.VsAdornments merged into Strokes.GUI

Other changes:
1) The extension will now only scan for achievements when compiling code that originates from a Strokes Achievement Project

PLEASE NOTE:
You might have to do a Solution Clean (right click Solution -> Clean), before you start the project the next time - some times the VSIX Deployer doesn't clean the target path properly.

Everyone please let me know if it works for you when you've pulled these changes.

**Comment by timdams** [comment]
Mmmm, did a clean build and the UI-pane shows up in VS, but no detection is kicks in.

**Comment by jonasswiatek** [comment]
You need to create a new achievement project. The "old" csproj file won't be
acknowledged by the extension any more
On Oct 7, 2011 8:30 AM, "Tim Dams" <
reply@reply.github.com>
wrote:

**Comment by timdams** [comment]
Check. works like a charm!
